# Default values for idta-aasx-server.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: adminshellio/aasx-server-blazor-for-demo
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: v3latest
  containerPort: 5001

fullnameOverride: idta-aasx-server

Deployment:
  name: idta-aasx-server
  app:  idta-aasx-server-app


service:
  type: NodePort
  port: 5001


ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 10m
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  tls:
    - hosts:
        - aaspe-server.factory-x.catena-x.net
      secretName: tls-secret-aaspe-server
  hosts:
    - host: aaspe-server.factory-x.catena-x.net
      paths:
        - path: /
          pathType: Prefix

# ingress:
#   enabled: false
#   className: ""
#   annotations: {}
#     # kubernetes.io/ingress.class: nginx
#     # kubernetes.io/tls-acme: "true"
#   hosts:
#     - host: chart-example.local
#       paths:
#         - path: /
#           pathType: ImplementationSpecific
#   tls: []
#   #  - secretName: chart-example-tls
#   #    hosts:
#   #      - chart-example.local


autoscaling:
  enabled: false

serviceAccount:
  # Specifies whether a service account should be created
  create: false